version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.8
  pre_build:
    commands:
      - echo Build started on 'date'
  build:
    commands:
      - echo Build started on `date`
      - pip install Flask
      - python app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
    - '**/*'