name: Release Binary to S3
 uses: mostlytyped/s3-put-action@v1.0.0
 with:
  args: --acl-public
 env:
  LOCAL_FILE: C:\Users\Tom\Desktop\html\languapps
  REMOTE_FILE: https://s3.us-east-1.amazonaws.com/languapps.com/gitpush
  AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  INCLUDE_SHA256: true